[project]
name = "airdrop-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "eth-utils>=5.2.0",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "web3>=7.10.0",
]
